    export const SignatureRules = [
      {
        provider: "shopee",
        fileType: "return",
        mustHave: ["เหตุผลในการยกเลิกคำสั่งซื้อ"],
        keyColumns: [
          "หมายเลขคำสั่งซื้อ",
          "ชื่อผู้ใช้ (ผู้ซื้อ)",
          "ช่องทางการชำระเงิน",
          "ตัวเลือกการจัดส่ง",
          "รหัสไปรษณีย์",
          "เวลาการชำระสินค้า",
          "เหตุผลในการยกเลิกคำสั่งซื้อ",
          "ชื่อสินค้า",
          "ชื่อตัวเลือก",
          "จำนวน",
        ],
        normalizedColumns: {
          orderId: "หมายเลขคำสั่งซื้อ",
          buyer: "ชื่อผู้ใช้ (ผู้ซื้อ)",
          paymentMethod: "ช่องทางการชำระเงิน",
          shippingOption: "ตัวเลือกการจัดส่ง",
          postalCode: "รหัสไปรษณีย์",
          isPaid: "เวลาการชำระสินค้า",
          cancelReason: "เหตุผลในการยกเลิกคำสั่งซื้อ",
          productName: "ชื่อสินค้า",
          variation: "ชื่อตัวเลือก",
          quantity: "จำนวน",
        },
      },
      {
        provider: "shopee",
        fileType: "order",
        mustHave: ["Hot Listing"],
        keyColumns: [
          "หมายเลขคำสั่งซื้อ",
          "ชื่อผู้ใช้ (ผู้ซื้อ)",
          "ช่องทางการชำระเงิน",
          "ตัวเลือกการจัดส่ง",
          "รหัสไปรษณีย์",
          "เวลาการชำระสินค้า",
          "เหตุผลในการยกเลิกคำสั่งซื้อ",
          "ชื่อสินค้า",
          "ชื่อตัวเลือก",
          "จำนวน",
        ],
        normalizedColumns: {
          orderId: "หมายเลขคำสั่งซื้อ",
          buyer: "ชื่อผู้ใช้ (ผู้ซื้อ)",
          paymentMethod: "ช่องทางการชำระเงิน",
          shippingOption: "ตัวเลือกการจัดส่ง",
          postalCode: "รหัสไปรษณีย์",
          paidTime: "เวลาการชำระสินค้า",
          cancelReason: "เหตุผลในการยกเลิกคำสั่งซื้อ",
          productName: "ชื่อสินค้า",
          variation: "ชื่อตัวเลือก",
          quantity: "จำนวน",
        },
      },
      {
        provider: "lazada",
        fileType: "order",
        mustHave: ["rtsSla", "ttsSla"],
        keyColumns: [
          "orderItemId",
          "deliveryType",
          "customerName",
          "payMethod",
          "shippingPostCode",
          "paidPrice",
          "itemName",
          "variation",
        ],
        normalizedColumns: {
          orderId: "orderItemId",
          buyer: "customerName",
          paymentMethod: "payMethod",
          shippingOption: "deliveryType",
          postalCode: "shippingPostCode",
          isPaid: "paidPrice",
          productName: "itemName",
          variation: "variation",
          quantity: "-",
        },
      },
      {
        provider: "lazada",
        fileType: "return",
        mustHave: ["Return Item ID", "Return Order Date"],
        keyColumns: ["Order ID", "buyerName", "Return Reason", "Item Name", "Paid Price + Shipping Fee"],
        normalizedColumns: {
          orderId: "Order ID",
          buyer: "buyerName",
          paymentMethod: "-",
          shippingOption: "-",
          postalCode: "-",
          isPaid: "Paid Price + Shipping Fee",
          cancelReason: "Return Reason",
          productName: "Item Name",
          variation: "-",
          quantity: "-",
        },
      },
      {
        provider: "tiktok",
        fileType: "order",
        mustHave: ["RTS Time"],
        keyColumns: [
          "Order ID",
          "Buyer Username",
          "Payment Method",
          "Product Name",
          "Variation",
          "Quantity",
        ],
        normalizedColumns: {
          orderId: "Order ID",
          buyer: "Buyer Username",
          paymentMethod: "Payment Method",
          shippingOption: "-",
          postalCode: "-",
          paidTime: "-",
          cancelReason: "-",
          productName: "Product Name",
          variation: "Variation",
          quantity: "Quantity",
        },
      },
            {
        provider: "tiktok",
        fileType: "return",
        mustHave: ["Dispute Status"],
        keyColumns: ["Order ID", "Buyer Username", "Return Reason", "Payment Method", "Refund Time", "Product Name", "Return Quantity"],
        normalizedColumns: {
          orderId: "Order ID",
          buyer: "Buyer Username",
          paymentMethod: "-",
          shippingOption: "-",
          postalCode: "-",
          isPaid: "Refund Time",
          cancelReason: "Return Reason",
          productName: "Product Name",
          variation: "-",
          quantity: "Return Quantity",
        },
      },
    ];