export const SignatureRules = [
  {
    provider: "shopee",
    mustHave: ["ชื่อตัวเลือก"],
    keyColumns: [
      "หมายเลขคำสั่งซื้อ",
      "ชื่อผู้ใช้ (ผู้ซื้อ)",
      "ช่องทางการชำระเงิน",
      "รหัสไปรษณีย์",
      "สถานะการสั่งซื้อ",
      "สถานะการคืนเงินหรือคืนสินค้า",
      "ชื่อสินค้า",
      "ชื่อตัวเลือก",
      "จำนวน",
    ],
    normalizedColumns: {
      orderId: "หมายเลขคำสั่งซื้อ",
      buyer: "ชื่อผู้ใช้ (ผู้ซื้อ)",
      paymentMethod: "ช่องทางการชำระเงิน",
      postalCode: "รหัสไปรษณีย์",
      status: "สถานะการสั่งซื้อ",
      cancelReason: "สถานะการคืนเงินหรือคืนสินค้า",
      productName: "ชื่อสินค้า",
      variation: "ชื่อตัวเลือก",
      quantity: "จำนวน",
    },
  },
  {
    provider: "lazada",
    fileType: "order",
    mustHave: ["rtsSla", "ttsSla"],
    keyColumns: [
      "orderItemId",
      "customerName",
      "payMethod",
      "shippingPostCode",
      "status",
      "buyerFailedDeliveryReturnInitiator",
      "itemName",
      "variation",
    ],
    normalizedColumns: {
      orderId: "orderItemId",
      buyer: "customerName",
      paymentMethod: "payMethod",
      postalCode: "shippingPostCode",
      status: "status",
      cancelReason: "buyerFailedDeliveryReturnInitiator",
      productName: "itemName",
      variation: "variation",
      quantity: "-",
    },
  },
  {
    provider: "tiktok",
    mustHave: ["RTS Time"],
    keyColumns: [
      "Order ID",
      "Order Status",
      "Buyer Username",
      "Payment Method",
      "Product Name",
      "Variation",
      "Quantity",
      "Cancelation/Return Type",
    ],
    normalizedColumns: {
      orderId: "Order ID",
      buyer: "Buyer Username",
      paymentMethod: "Payment Method",
      postalCode: "-",
      status: "Order Status",
      cancelReason: "Cancelation/Return Type",
      productName: "Product Name",
      variation: "Variation",
      quantity: "Quantity",
    },
  }
];
